name: Dockermain
on:
  push:
    branches: ['main']
jobs:
  docker:
    strategy:
    matrix:
      include:
      - arch    : amd64
        mode    : build-and-test
      - arch    : arm64
        variant : v8
        mode    : build-only
    runs-on: ubuntu-latest
    env:
      PLATFORM  : linux/${{ matrix.arch }}${{ (matrix.variant != '' && format('/{0}', matrix.variant)) || '' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU        
        uses: docker/setup-qemu-action@v2
        with:
          #platforms: 'arm64,arm'
          platforms: ${{ matrix.arch }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: eggcold/test:test1
          platforms  : ${{ env.PLATFORM }}

          